---
##############################
# Configuration for Bot #
# Add bots to your MCPE server #
##############################

# Make the bots sneak
sneak: true
# Make the bots un-sneak
unsneak: true
# Make the bots rotate
rotation: true
distance: 16
# Make the bots swing
swing: true
# Add circle particles to your bots
particles: true
# damage mode for bots
damage: false
...